### ISSUE TITLE
Cyclic dependency in tutorial #4

### ISSUE THREAD

**Issue by timopl** [badoo/RIBs#137]
Hello everyone! 

I'm not sure if this is an issue or intended behavior but anyway. 
I'm not using Dagger 2 in my project so I've tried to follow the tutorials using manual DI and found an interesting thing. In tutorial #4 where communication between RIBs illustrated, there is a cyclic dependency:
```
ParentIntercator --(needs)--> ParentRouter --(needs)--> ChildBuilder --(needs)--> OutputConsumer --(declared_in)--> ParentInteractor
```

It builds & works fine because ChildBuilder gets constructed without asking for its dependencies. However, if you try to ask them in constructor, app will crash in runtime.

**Comment by zsoltk** [comment]
Yes, Dagger helps you with this. 

With manual DI you can get around it by constructing the OutputConsumer in your ParentBuilder and passing the same instance to both places:

ParentBuilder --(passes OutputConsumer)--> ChildBuilder
ParentBuilder --(passes ChildBuilder)--> ParentRouter
ParentBuilder --(passes ParentRouter)--> ParentInteractor
ParentBuilder --(passes OutputConsumer)--> ParentInteractor

**Comment by timopl** [comment]
Yeah, that makes sense. 
Thanks for the response, I’ll then close the issue
