### ISSUE TITLE
router.push keeps all views attached

### ISSUE THREAD

**Issue by timopl** [badoo/RIBs#145]
Hello there!

I have an issue where `router.push` just stacks views on top of each other and you even can click through the views. 

Not sure if it is desired behavior, but I expected it to work similar to fragment manager: when you push, current view gets detached and new view is attached. When you press "Back", previous view gets attached with restored state.

Here is the repo to reproduce: https://github.com/timopl/ribs-push

Thanks!

**Comment by zsoltk** [comment]
Hey @timopl! This is not a bug, you have the wrong setup.

This is what you wanted to do:

`Root`

- `Child 1`
- `Child 2`

In this scenario if you push `Child1`, then `Child2`, then both of them are in the back stack of `Root`, so `Child1` will be correctly detached from the view.

In your setup however you have:

`Root`
- `Child1`
  - `Child2`

In your setup the parent of `Child2` is `Child1`. Because of this, when you push `Child2`, you do not add it to the back stack of `Root`, but to the back stack of `Child1`. 

Root's back stack is not modified in the process, so it still has `Child1` as the latest (active) one. And now `Child1` is in a configuration to activate `Child2`, so it adds that as its own child, and now both of them are on the screen.

As soon as you move them under the same parent (`Root`) as siblings, it will work as you'd expect.

**Comment by zsoltk** [comment]
Also worth to mention you don't need to channel your UI event through a `Feature` to produce a navigation event, that just adds lots of unnecessary steps with no extra benefit. You can bind ui event to `router.push` directly. `Feature` is best used for things that are related to changing state.

**Comment by timopl** [comment]
Nice catch about feature and routing events, thank you! 

So, this means that if for eg I have root screen, login screen and restore password screen and I want to go from login to restore password, I need bubble up an event from login to root and root will push the restore password screen replacing the login?

**Comment by zsoltk** [comment]
Yep! That's the simplest way. At some point in real life you might want to have a `LoginContainer` that does exactly this and move it one level deeper under `Root`. 

Doing so will make your real `Root` leaner in that it only needs to know about the switch between `Logged out` and `Logged in` routing states, and password screen becomes an implementation detail of your logged out one (i.e. the `LoginContainer`).

**Comment by timopl** [comment]
Yeah, makes sense, thanks!

**Comment by Gaket** [comment]
> Hey @timopl! This is not a bug, you have the wrong setup.
> 
> This is what you wanted to do:
> 
> `Root`
> 
> * `Child 1`
> * `Child 2`
> 
> In this scenario if you push `Child1`, then `Child2`, then both of them are in the back stack of `Root`, so `Child1` will be correctly detached from the view.
> 
> In your setup however you have:
> 
> `Root`
> 
> * `Child1`
>   
>   * `Child2`
> 
> In your setup the parent of `Child2` is `Child1`. Because of this, when you push `Child2`, you do not add it to the back stack of `Root`, but to the back stack of `Child1`.
> 
> Root's back stack is not modified in the process, so it still has `Child1` as the latest (active) one. And now `Child1` is in a configuration to activate `Child2`, so it adds that as its own child, and now both of them are on the screen.
> 
> As soon as you move them under the same parent (`Root`) as siblings, it will work as you'd expect.

Does it basically mean that as far as I want one screen to replace another with a back stack, I need to have those screens as siblings?

**Comment by zsoltk** [comment]
@Gaket Yes, if it's the same back stack. Look at it from the parent's perspective. The parent has control over its own back stack and what things can go there - these are any other RIB that it can build (satisfying their dependencies) and it wants to build (matched to a Configuration).

Although the above does not mean that you always need to have everything that can cover the full screen nested under the same parent. That would result in one "super node" and wouldn't be efficient. You have some other options:

1. any level in the tree can be just a container which adds nothing to the view directly (its `ViewFactory` is null), so its whole available screen space is given to its children. 
2. you can use Portals to open something full screen even if the parent itself has access to a portion of the screen.

**Comment by Gaket** [comment]
Thanks, will try it out.
