### ISSUE TITLE
Deeplink support

### ISSUE THREAD

**Issue by Gaket** [badoo/RIBs#151]
Hey guys! Thanks for the work you're doing!

I have a question about Deeplinking. I've heard that the Workflow / Steps set up from the original repo is not going to work in Badoo version of Ribs. Is it a correct sentence? Can you give some direction on how to implement it? And I guess that might be a good idea to create a separate Tutorial page for that somewhere in the future.

https://github.com/uber/RIBs/wiki/Android-Tutorial-4

**Comment by zsoltk** [comment]
Hey @Gaket!

Where did you hear this? :) It should definitely be working.

1. Take a look at the AndroidManifest.xml in `app-example`, you'll see an intent filter for deep links that's going to `RootActivity`.
2. Check the overridden `workflowFactory` in `RootActivity` to see what it catches. It has comments with examples of what you need to type in console to test them.

Tell me if something doesn't work!
