### ISSUE TITLE
Question: Does this work with Bolt's RIB scheme analyzer?

### ISSUE THREAD

**Issue by ericntd** [badoo/RIBs#224]
https://plugins.jetbrains.com/plugin/15411-bolt-toolkit

**Comment by zsoltk** [comment]
Bolt seem to be using Uber's RIBs, not ours. Their plugin is also probably for their own developers, as there's no public information on it I could find. 

Btw if you have both their plugin and ours installed, you can run into issues with new RIB creation (I wonder if your other issue #223 has anything to do with that?)

**Comment by ericntd** [comment]
Thanks for responding, this is too specific for now, closing
