### ISSUE TITLE
Compose container + Android container

### ISSUE THREAD

**Issue by zsoltk** [badoo/RIBs#332]
**Works as expected:**

- AndroidRibView → AndroidRibView
- AndroidRibView → ComposeRibView
- AndroidRibView → viewless container → (any) RibView
- ComposeRibView → ComposeRibView
- ComposeRibView → AndroidRibView 

**Broken:**

- ComposeRibView → viewless container → (any) RibView

**What happens:**

- Nothing is attached to the view

**Workaround?**

- Creating an empty view for the container works, but isn't optimal

**Further info**

- Probably it's attached and detached right after, since the order of attach/detach was designed for ViewGroup-based animations, which don't work well together with Compose mechanics.
- I tried to fix it in the code that I reverted in 06ebd0fac (accidentally pushed), but only got to partial success: initial attach worked after adding a null check for removal, but switching children inside the viewless container didn't update the view, the first one got stuck.

**Comment by SamuPS** [comment]
Fixed with #339 approach
