### ISSUE TITLE
Dialog events are not propagated after activity recreation

### ISSUE THREAD

**Issue by lukaville** [badoo/RIBs#42]
Steps to reproduce:
* Enable "Don't keep activities"
* Open app-example app
* Click on "Rib dialog"
* Minimize and maximize the app
* Try to click on dialog buttons/back button

For some reason, it stops working after activity restart

**Comment by jeksor** [comment]
Reproduced even without DKA.
- Open app-example app
- Click on "Rib dialog"
- Rotate the device
- Try to click on dialog buttons/back button
